"""
run_test_suite_frontier_voltage_boost_laplace_nd.py

Dimension-agnostic runner for FrontierVoltageBoostLaplaceND.
Accepts maps generated by init_test_suite.py for any dimensionality.
Dimensionality is inferred from the .npy grid shape; start/end columns
are read from the CSV and mapped to (x, y) or (x, y, z) accordingly.

Usage (from project root):
    python "Test Suite/run_test_suite_frontier_voltage_boost_laplace_nd.py" `
        --maps_dir "Test Suite/output/2d_maps" `
        --laplace_iters 200 `
        --epsilon 0.0001

    python "Test Suite/run_test_suite_frontier_voltage_boost_laplace_nd.py" `
        --maps_dir "Test Suite/output/3d_maps" `
        --laplace_iters 200 `
        --epsilon 0.0001
"""

import argparse
import csv
import os
import importlib.util
import numpy as np

# ---------------------------------------------------------------------------
# Load packages
# ---------------------------------------------------------------------------

from map_generation import Map2D, Map3D

_here = os.path.dirname(os.path.abspath(__file__))

_fvb_path = os.path.normpath(
    os.path.join(_here, '..', 'Algorithms', 'Frontier Voltage Boost', 'ndfrontiervoltageboostlaplace.py')
)
_fvb_spec = importlib.util.spec_from_file_location('ndfvb', _fvb_path)
_fvb_mod  = importlib.util.module_from_spec(_fvb_spec)
_fvb_spec.loader.exec_module(_fvb_mod)
FrontierVoltageBoostLaplaceND = _fvb_mod.FrontierVoltageBoostLaplaceND

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(
    description='Run N-D Frontier Voltage Boost Laplace on a folder of maps.'
)
parser.add_argument('--maps_dir',      required=True,
                    help='Folder containing start_end_points.csv and .npy map files.')
parser.add_argument('--laplace_iters', required=True, type=int,
                    help='Number of Laplace iterations per wavefront step (n_l).')
parser.add_argument('--epsilon',       required=True, type=float,
                    help='Convergence threshold — cell is solved when φ ≤ v_max - epsilon.')
parser.add_argument('--step_size',     type=float, default=1.0,
                    help='Gradient descent step size (default: 1.0).')
parser.add_argument('--no_bilinear',   action='store_true',
                    help='Disable N-linear interpolation for gradient descent (default: on).')
parser.add_argument('--output',        nargs='+', default=['maps', 'paths', 'phi'],
                    choices=['maps', 'paths', 'phi'],
                    help='Output types: maps, paths (overlay), phi (potential field). Default: all.')
args = parser.parse_args()

save_maps  = 'maps'  in args.output
save_paths = 'paths' in args.output
save_phi   = 'phi'   in args.output

maps_dir = os.path.abspath(args.maps_dir)
csv_path = os.path.join(maps_dir, 'start_end_points.csv')

if not os.path.isfile(csv_path):
    raise FileNotFoundError(f"No start_end_points.csv found in {maps_dir}")

output_dir = os.path.join(maps_dir, 'fvb_nd_results')
os.makedirs(output_dir, exist_ok=True)

print(f"Maps dir:      {maps_dir}")
print(f"laplace_iters: {args.laplace_iters}")
print(f"epsilon:       {args.epsilon}")
print(f"step_size:     {args.step_size}")
print(f"n-linear:      {not args.no_bilinear}")
print(f"Output:        {', '.join(args.output)}\n")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_COORD_COLS = [
    ('start_x', 'end_x'),
    ('start_y', 'end_y'),
    ('start_z', 'end_z'),
]


def _parse_point(row, headers, ndim):
    start, end = [], []
    for i in range(ndim):
        sc, ec = _COORD_COLS[i]
        if sc not in headers or ec not in headers:
            raise ValueError(f"CSV missing columns '{sc}'/'{ec}' for {ndim}D map")
        start.append(int(row[sc]))
        end.append(int(row[ec]))
    return tuple(start), tuple(end)


def _make_map(grid, start, end):
    if grid.ndim == 2:
        return Map2D(grid, start, end)
    if grid.ndim == 3:
        return Map3D(grid, start, end)
    raise ValueError(f"No Map class for {grid.ndim}D grids (only 2D/3D maps are generated)")


def _save_2d(algo, m, path, start, end, stem, out_dir, save_maps, save_paths, save_phi):
    from PIL import Image

    if save_maps:
        Image.fromarray(m.to_image(), mode='L').save(
            os.path.join(out_dir, f'{stem}_map.png')
        )
        print(f"  Saved map  → fvb_nd_results/{stem}_map.png")

    if save_paths:
        grey = m.to_image()
        rgb  = np.stack([grey, grey, grey], axis=2).copy()
        for pt in path:
            x, y = pt[0], pt[1]
            if 0 <= y < rgb.shape[0] and 0 <= x < rgb.shape[1]:
                rgb[y, x] = [128, 128, 255]
        rgb[start[1], start[0]] = [0, 255, 0]
        rgb[end[1],   end[0]]   = [255, 0, 0]
        Image.fromarray(rgb, mode='RGB').save(
            os.path.join(out_dir, f'{stem}_path.png')
        )
        print(f"  Saved path → fvb_nd_results/{stem}_path.png")

    if save_phi and algo._phi is not None:
        phi      = algo._phi
        phi_norm = (phi - phi.min()) / (phi.max() - phi.min() + 1e-9)
        Image.fromarray((phi_norm * 255).astype(np.uint8), mode='L').save(
            os.path.join(out_dir, f'{stem}_phi.png')
        )
        print(f"  Saved phi  → fvb_nd_results/{stem}_phi.png")


def _save_3d(algo, m, path, start, end, stem, out_dir, save_maps, save_paths, save_phi):
    from PIL import Image
    map_out  = os.path.join(out_dir, stem)
    os.makedirs(map_out, exist_ok=True)

    path_set = {tuple(pt) for pt in path}
    sx, sy, sz = start[0], start[1], start[2]
    ex, ey, ez = end[0],   end[1],   end[2]

    if save_maps:
        for z in range(m.depth):
            Image.fromarray(m.to_image_slice(z), mode='L').save(
                os.path.join(map_out, f'map_slice_{z:04d}.png')
            )
        print(f"  Saved map slices → fvb_nd_results/{stem}/map_slice_*.png")

    if save_paths:
        for z in range(m.depth):
            grey = m.to_image_slice(z)
            rgb  = np.stack([grey, grey, grey], axis=2).copy()
            for pt in path_set:
                x, y, pz = pt[0], pt[1], pt[2]
                if pz == z and 0 <= y < rgb.shape[0] and 0 <= x < rgb.shape[1]:
                    rgb[y, x] = [128, 128, 255]
            if sz == z:
                rgb[sy, sx] = [0, 255, 0]
            if ez == z:
                rgb[ey, ex] = [255, 0, 0]
            Image.fromarray(rgb, mode='RGB').save(
                os.path.join(map_out, f'path_slice_{z:04d}.png')
            )
        print(f"  Saved path slices → fvb_nd_results/{stem}/path_slice_*.png")

    if save_phi and algo._phi is not None:
        phi      = algo._phi
        phi_norm = (phi - phi.min()) / (phi.max() - phi.min() + 1e-9)
        phi_img  = (phi_norm * 255).astype(np.uint8)
        for z in range(m.depth):
            Image.fromarray(phi_img[z], mode='L').save(
                os.path.join(map_out, f'phi_slice_{z:04d}.png')
            )
        print(f"  Saved phi slices  → fvb_nd_results/{stem}/phi_slice_*.png")


# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

with open(csv_path, newline='') as f:
    reader  = csv.DictReader(f)
    headers = reader.fieldnames
    rows    = list(reader)

for row in rows:
    map_name      = row['map_name']
    stem          = os.path.splitext(map_name)[0]
    grid          = np.load(os.path.join(maps_dir, map_name))
    ndim          = grid.ndim
    start, end    = _parse_point(row, headers, ndim)
    m             = _make_map(grid, start, end)

    print(f"{map_name}  ({ndim}D)  start={start}  end={end}")

    algo = FrontierVoltageBoostLaplaceND(
        m,
        n_l=args.laplace_iters,
        epsilon=args.epsilon,
        step_size=args.step_size,
        bilinear_interpolation=not args.no_bilinear,
    )
    path = algo.solve()

    if path is None:
        print(f"  WARNING: no path found\n")
        continue

    print(f"  Path length: {len(path)} steps")

    if ndim == 2:
        _save_2d(algo, m, path, start, end, stem, output_dir, save_maps, save_paths, save_phi)
    elif ndim == 3:
        _save_3d(algo, m, path, start, end, stem, output_dir, save_maps, save_paths, save_phi)

    print()

print("Done.")
